/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashProfileRouteImport } from './routes/_dash/profile'
import { Route as DashMentorRouteImport } from './routes/_dash/mentor'
import { Route as DashManageUsersRouteImport } from './routes/_dash/manage-users'
import { Route as DashInternRouteImport } from './routes/_dash/intern'
import { Route as DashAdminRouteImport } from './routes/_dash/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashProfileRoute = DashProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashRoute,
} as any)
const DashMentorRoute = DashMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => DashRoute,
} as any)
const DashManageUsersRoute = DashManageUsersRouteImport.update({
  id: '/manage-users',
  path: '/manage-users',
  getParentRoute: () => DashRoute,
} as any)
const DashInternRoute = DashInternRouteImport.update({
  id: '/intern',
  path: '/intern',
  getParentRoute: () => DashRoute,
} as any)
const DashAdminRoute = DashAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof DashAdminRoute
  '/intern': typeof DashInternRoute
  '/manage-users': typeof DashManageUsersRoute
  '/mentor': typeof DashMentorRoute
  '/profile': typeof DashProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof DashAdminRoute
  '/intern': typeof DashInternRoute
  '/manage-users': typeof DashManageUsersRoute
  '/mentor': typeof DashMentorRoute
  '/profile': typeof DashProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_dash/admin': typeof DashAdminRoute
  '/_dash/intern': typeof DashInternRoute
  '/_dash/manage-users': typeof DashManageUsersRoute
  '/_dash/mentor': typeof DashMentorRoute
  '/_dash/profile': typeof DashProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/intern'
    | '/manage-users'
    | '/mentor'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/intern'
    | '/manage-users'
    | '/mentor'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/login'
    | '/signup'
    | '/_dash/admin'
    | '/_dash/intern'
    | '/_dash/manage-users'
    | '/_dash/mentor'
    | '/_dash/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/profile': {
      id: '/_dash/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashProfileRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/mentor': {
      id: '/_dash/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof DashMentorRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/manage-users': {
      id: '/_dash/manage-users'
      path: '/manage-users'
      fullPath: '/manage-users'
      preLoaderRoute: typeof DashManageUsersRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/intern': {
      id: '/_dash/intern'
      path: '/intern'
      fullPath: '/intern'
      preLoaderRoute: typeof DashInternRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/admin': {
      id: '/_dash/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof DashAdminRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashAdminRoute: typeof DashAdminRoute
  DashInternRoute: typeof DashInternRoute
  DashManageUsersRoute: typeof DashManageUsersRoute
  DashMentorRoute: typeof DashMentorRoute
  DashProfileRoute: typeof DashProfileRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashAdminRoute: DashAdminRoute,
  DashInternRoute: DashInternRoute,
  DashManageUsersRoute: DashManageUsersRoute,
  DashMentorRoute: DashMentorRoute,
  DashProfileRoute: DashProfileRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
